ng1:
	npm install -g @angular/cli
	ng new coronavirus-cases
ng2:
	cd coronavirus-cases && ng serve --open
ng3:
	cd coronavirus-cases && ng g component cases
	cd coronavirus-cases && ng g component cases-details
	cd coronavirus-cases && ng g component add-cases
	cd coronavirus-cases && ng g component edit-cases
	cd coronavirus-cases && ng g component cases-stat
ng4:
	cd coronavirus-cases && ng g service api


